---
- name: install postgresql
  apt:
    name={{ item }}
    state=present
  with_items:
    - postgresql

- name: ensure mysql is running
  service:
    name=postgresql
    state=running

- include: vagrant.yml
  when: env == 'vagrant'

- include: prod.yml
  when: env != 'vagrant'

- include: common.yml
