---
# For all machines in ansible inventory

- hosts: app_forex

  gather_facts: no

  sudo: true
  sudo_user: root

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - { role: app_forex, when: env == 'app_forex' }
