---
# For all machines in ansible inventory

- hosts: all

  gather_facts: no

  sudo: true
  sudo_user: root

# Tasks before roles are applied
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - devserver
