---
- name: install apache2
  apt:
    name={{ item }}
    state=present
  with_items:
    - apache2

- name: install php5 for apache2
  apt:
    name={{ item }}
    state=present
  notify: reload apache2
  with_items:
    - php5
    - php5-gd
    - php5-mcrypt

- name: enable php modules
  command: php5enmod {{ item }}
  notify: reload apache2
  with_items:
    - mcrypt
    - gd

- name: copy apache2 and php configuration
  copy:
    src={{ item }}
    dest=/etc/{{ item }}
    force=yes
  notify: reload apache2
  with_items:
#    - apache2/apache2.conf
#    - apache2/ports.conf
    - php5/apache2/php.ini
    - php5/cli/php.ini

- name: enable apache modules
  apache2_module:
    name={{ item }}
    state=present
  notify: reload apache2
  with_items:
    - rewrite
    - ssl
    - status
    - cgi
